### ISSUE TITLE
tabular data/ noisy instances/ new datasets

### ISSUE THREAD

**Issue by nazaretl** [nazmul-karim170/UNICON-Noisy-Label#1]
Hi,
thanks for sharing your implementation. I have some questions about it:

1.	Does it also work on tabular data?
2.	Is the code tailored to the datasets used in the paper or can one apply it to any data?
3.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by nazmul-karim170** [comment]
It should work on tabular data. You need to change the data loader
accordingly.
 It is possible to identify the indices of clean and noisy samples, just
don’t shuffle the data.

Best,
Nazmul

**Comment by nazaretl** [comment]
may thanks!
