### ISSUE TITLE
Question about SSL algorithm

### ISSUE THREAD

**Issue by RumengYi** [nazmul-karim170/UNICON-Noisy-Label#2]
Hi, I noticed that the SSL method you used in your code is MixMatch, which is similar to DivideMix, rather than FixMatch in your paper?

**Comment by nazmul-karim170** [comment]
Yeah. That is right. But the augmentation is different for prediction and
training. This is more similar to fixmatch.

**Comment by RumengYi** [comment]
Thank you very much！
