### ISSUE TITLE
Cifar10 90% noise rate Performance

### ISSUE THREAD

**Issue by chaserLX** [nazmul-karim170/UNICON-Noisy-Label#5]
Hi
Running Train_cifar.py without changing the experimental parameters, the best result of 20% noise rate in cifar10 dataset is 94.42%, and the best result of 90% noise rate is 89.10%, which is quite different from the results shown in the paper. Can you give me the command to run the sample code for 20% noise rate and 90% noise rate?

**Comment by nazmul-karim170** [comment]
For 20%, sometimes the results fluctuate, for 90% I will look into it. It
should be at least 90%.

**Comment by nazmul-karim170** [comment]
For high noise rate, you need to change the dataloader_cifar.py. For unlabelled data and replace
 "batch_size= int(self.batch_size/(2*sample_ratio))"  with "batch_size= int(self.batch_size/(sample_ratio))" in line 323.
