### ISSUE TITLE
Implementation of dataloader code

### ISSUE THREAD

**Issue by bonggeon** [nazmul-karim170/UNICON-Noisy-Label#8]
Hi. thanks for interesting paper and available code.

I have a question for dataloader code.

I think this code should be added in dataloader code.
pred_idx = pred_idx[:size_pred]

for example, in dataloader_cifar.py line 169
self.train_data = train_data[pred_idx]

In github code, last few pred_idx are 0.

This should be applied to all the dataloader code.

If I misunderstood something, please let me know

thank you.

**Comment by nazmul-karim170** [comment]
I am sorry I did not get your question.

Nazmul

**Comment by bonggeon** [comment]
In dataloader_cifar.py
line 139
pred_idx  = np.zeros(int(self.sample_ratio*num_sample))

but I think
size_pred < int(self.sample_ratio*num_sample)

so, pred_idx[size_pred:] are all zeros

this affects line 169
self.train_data = train_data[pred_idx]

If I have misunderstanding, I'm sorry
but please think about it and let me know.

**Comment by nazmul-karim170** [comment]
You can use append to a list instead of array initialization.

Like,

pred_idx = []

pred_idx.append()

**Comment by bonggeon** [comment]
I got it. thanks!
